### ISSUE TITLE
Error u-boot-1_2018.05-r0 do_patch: Function failed: patch_do_patch

### ISSUE THREAD

**Issue by gil0109** [mirzak/mender-raspberrypi-manifest#1]
ERROR: u-boot-1_2018.05-r0 do_patch: Command Error: 'quilt --quiltrc /home/xxx                                                                                        /recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0003-Integration-of-Mender-boot-code-into-U-Boot.patch
patching file include/env_default.h
Hunk #1 succeeded at 9 with fuzz 2 (offset -1 lines).
Hunk #2 FAILED at 24.
1 out of 2 hunks FAILED -- rejects in file include/env_default.h
patching file scripts/Makefile.autoconf
Hunk #1 succeeded at 109 (offset -2 lines).
Patch 0003-Integration-of-Mender-boot-code-into-U-Boot.patch does not apply (enf
ERROR: u-boot-1_2018.05-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/xxxxx/mender-raspberrypi/build/tmp/
ERROR: Task (/home/xxxxx/mender-raspberrypi/build/../layers/poky/meta/recipes-
NOTE: Tasks Summary: Attempted 886 tasks of which 0 didn't need to be rerun and 1 failed.

**Comment by mirzak** [comment]
Guess this was on master? 

I can recommend building from one of the stable branches, rocko would be best as that is the latest

**Comment by gil0109** [comment]
Thanks, will try with rocko branch.  And thank you for this repo :)

**Comment by mirzak** [comment]
Glad it is useful :)

**Comment by gil0109** [comment]
My goal is to emulate my Raspbian image I created for digital signage but with patching and managment using Mender,io

Read Only image (using overlay)
Chromium (or webkit) in Kiosk mode with GPU HW acceleration
Wifi 802.11X 
Some scripting to manage timezone's (have to deal with three different Timezones) and different URLs.
Disable Bluetooth
ufw.

**Comment by mirzak** [comment]
Did the rocko branch work for you?

**Comment by gil0109** [comment]
The rocko branch was incompatible with the version of WPE I was using.  

I have switched to one that is compatible to the rocko branch but I am having issues with WPE-webkit displaying my mp4 files.  So I am trying to solve that first, then layer on the mender recipe.

I will add the mender layer tonight and see if it fixes this issue just so we can close this issue.  Thank you for your patience.

**Comment by mirzak** [comment]
No rush on my side, just curious :)

**Comment by gil0109** [comment]
Thanks.  Nothing is simple when you are learning.  It seems like every layer I want to add has issues and/or bugs I need resolved.  But the learning and help I get from people like you makes it soo much better.  Thanks again.

**Comment by gil0109** [comment]
Confirmed, using rocko fixed the issue.  Thank you.  

Please close this issue.

**Comment by mirzak** [comment]
Thanks for reporting back, good luck in your continued work :)
